Inject metrics registry in route based controllers
paritytech/substrate-api-sidecar pull request #1477
Opened 2024-08-15 09:53 UTC by filvecchiato

This PR allows for route-specific metrics to be emitted from the controllers, by injecting in the Response object (in locals) the metrics registry, making it available for each request received in case the prometheus flag is true

2024-08-15 15:06 UTC, TarikGul commented on src/controllers/blocks/BlocksController.ts
> +import client from 'prom-client';
If we are using `client` here just as a type - lets do `import type client from ''prom-client`

2024-08-15 15:06 UTC, TarikGul commented on src/controllers/blocks/BlocksController.ts
> +	private getLatestBlock: RequestHandler<
I think we can abstract this into `src/types/request.ts`

2024-08-15 15:08 UTC, TarikGul commented on src/controllers/blocks/BlocksController.ts
> +		const paraIdArg = paraId !== undefined ? this.parseNumberOrThrow(paraId, 'paraId must be an integer') : undefined;
```suggestion
		const paraIdArg = paraId  ? this.parseNumberOrThrow(paraId, 'paraId must be an integer') : undefined;
```

2024-08-15 15:11 UTC, TarikGul commented on src/controllers/blocks/BlocksController.ts
> +	private getBlockById: RequestHandler<
We can also make this Generic so you don't have to write it twice:

type IBlockRequestHandler<T> = {
  T,
  unknown,
  unknown,
  BlockQueryParams,
  Metrics
}

2024-08-15 15:12 UTC, TarikGul commented on src/controllers/blocks/BlocksController.ts
> +	private getBlocks: RequestHandler<
Same with this type

2024-08-15 15:12 UTC, TarikGul commented on src/controllers/blocks/BlocksRawExtrinsicsController.ts
> +	private getBlockRawExtrinsics: RequestHandler<
Same with this Type

2024-08-15 15:12 UTC, TarikGul requested changes
Overall, really great job. Just some nits for the types.

2024-08-16 07:43 UTC, filvecchiato commented on src/controllers/blocks/BlocksController.ts
> +	private getBlockById: RequestHandler<
Created a generic type for the request with metrics that extends the RequestHandler

2024-08-16 11:58 UTC, TarikGul approved these changes
Great job, LGTM 🚀

2024-08-19 10:18 UTC, Imod7 approved these changes
LGTM! Just two small comments.

2024-08-19 11:42 UTC, filvecchiato commented on src/controllers/blocks/BlocksController.ts
> +				'sas_extrinsics_per_block_count'
Nice catch, I renamed them!

2024-08-19 11:46 UTC, merged